### ISSUE TITLE
FTB Loader hangs after adding FTB Ultimine

### ISSUE THREAD

**Issue by Dr69onS6mur6i** [VazkiiMods/Bliss#106]
I downloaded the most recent version of FTB Ultimine and added it to the mod directory. Before I added it the pack loaded just fine. After adding the mod the FTB Launcher hangs with no obvious errors. Log file attached.

[console.log](https://github.com/VazkiiMods/Bliss/files/8811124/console.log)

**Comment by gamingoninsulin** [comment]
ive added the mod and disabled music triggers due to some music bugs but i get no crash and if i check you log 

i see 
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method
and i think you have lithium mod installed is that correct?

**Comment by Dr69onS6mur6i** [comment]
If lithium IS installed it wasn't done by me. Ultimine is the only extra mod I downloaded.

**Comment by gamingoninsulin** [comment]
If i check the mod list i have i dont see lithium try disable it and check your mod list if any other mod dsables as well if so it was installed by that other mod that disables  as well if not you can remove lithium savely

**Comment by MisterObvious25** [comment]
This error seems to be a false positive. I also had a similar error when trying to add mods to the pack. 

1. Try to disable both 'Its the little things' and 'Radium Reforged' 
2. Launch the game with your newly added mods
3. it will show what the actual error is.

In my case it was a forge version error(a newer forge version was necessary)

Hope this helps
